mysql:
  host: localhost
  port: 3306
  user: root
  password: ''
  database: vulnbot_db
  socket: /home/jc/attacker-tools/.mysql/mysql.sock
  charset: utf8mb4
  connect_timeout: 30
  pool_size: 10
  max_overflow: 20
